"""Add ondelete cascade to foreign keys, fix vitals patient_id type

Revision ID: 370d3d1ecdbd
Revises: 7efbc59df17b
Create Date: 2026-07-01 12:11:33.870200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370d3d1ecdbd'
down_revision = '7efbc59df17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('general_assessments_vitals_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vitals', ['vitals_id'], ['vitals_id'], ondelete='CASCADE')

    with op.batch_alter_table('overweight_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('overweight_assessments_vitals_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vitals', ['vitals_id'], ['vitals_id'], ondelete='CASCADE')

    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vitals_patient_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['patient_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vitals_patient_id_fkey'), 'patients', ['patient_id'], ['patient_id'])

    with op.batch_alter_table('overweight_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('overweight_assessments_vitals_id_fkey'), 'vitals', ['vitals_id'], ['vitals_id'])

    with op.batch_alter_table('general_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('general_assessments_vitals_id_fkey'), 'vitals', ['vitals_id'], ['vitals_id'])

    # ### end Alembic commands ###
