"""Initial Tables

Revision ID: 7efbc59df17b
Revises: 
Create Date: 2026-06-30 15:05:33.893130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efbc59df17b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('vitals',
    sa.Column('vitals_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('vitals_id')
    )
    op.create_table('general_assessments',
    sa.Column('general_assessment_id', sa.Integer(), nullable=False),
    sa.Column('vitals_id', sa.Integer(), nullable=False),
    sa.Column('general_health', sa.String(length=20), nullable=False),
    sa.Column('drug_usage', sa.String(length=5), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['vitals_id'], ['vitals.vitals_id'], ),
    sa.PrimaryKeyConstraint('general_assessment_id'),
    sa.UniqueConstraint('vitals_id')
    )
    op.create_table('overweight_assessments',
    sa.Column('overweight_assessment_id', sa.Integer(), nullable=False),
    sa.Column('vitals_id', sa.Integer(), nullable=False),
    sa.Column('general_health', sa.String(length=20), nullable=True),
    sa.Column('diet_history', sa.String(length=5), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['vitals_id'], ['vitals.vitals_id'], ),
    sa.PrimaryKeyConstraint('overweight_assessment_id'),
    sa.UniqueConstraint('vitals_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overweight_assessments')
    op.drop_table('general_assessments')
    op.drop_table('vitals')
    op.drop_table('patients')
    # ### end Alembic commands ###
